apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlapify-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlapify-client
  template:
    metadata:
      labels:
        app: sqlapify-client
    spec:
      containers:
      - name: sqlapify-client
        image: yidoughi/sqlapify-client:latest
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001 
        command: ["start.sh"]
        envFrom:
          - configMapRef:
              name: sqlapify-client-config
          - secretRef:
              name: sqlapify-client-secrets
        ports:
          - containerPort: 8001
