apiVersion: v1
kind: Service
metadata:
  name: sqlapify-client
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
spec:
  selector:
    app: sqlapify-client
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001   
  type: LoadBalancer